In [2]:
import os
import pandas as pd
import kagglehub

caminho_dados = kagglehub.dataset_download("olistbr/brazilian-ecommerce")
print(f"Diretório base: {caminho_dados}\n")

arquivos = [f for f in os.listdir(caminho_dados) if f.endswith('.csv')]
print(f"Arquivos CSV disponíveis no dataset:")
for arquivo in arquivos:
    print(f" - {arquivo}")

Diretório base: /home/guizzys/.cache/kagglehub/datasets/olistbr/brazilian-ecommerce/versions/2

Arquivos CSV disponíveis no dataset:
 - olist_sellers_dataset.csv
 - olist_order_items_dataset.csv
 - olist_orders_dataset.csv
 - olist_order_reviews_dataset.csv
 - olist_order_payments_dataset.csv
 - olist_geolocation_dataset.csv
 - olist_customers_dataset.csv
 - olist_products_dataset.csv
 - product_category_name_translation.csv

In [3]:
df_pedidos = pd.read_csv(os.path.join(caminho_dados, "olist_orders_dataset.csv"))
df_itens = pd.read_csv(os.path.join(caminho_dados, "olist_order_items_dataset.csv"))

print("DataFrames 'df_pedidos' e 'df_itens' carregados na memória!")

DataFrames 'df_pedidos' e 'df_itens' carregados na memória!

In [4]:
print("--- AMOSTRA: TABELA DE PEDIDOS ---")
display(df_pedidos.head(3))

print("\n--- ESTRUTURA DOS DADOS ---")
df_pedidos.info()

print("\n--- CONTAGEM DE VALORES NULOS ---")
display(df_pedidos.isnull().sum().to_frame("Nulos").T)

--- AMOSTRA: TABELA DE PEDIDOS ---

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

--- ESTRUTURA DOS DADOS ---
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

--- CONTAGEM DE VALORES NULOS ---

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
Nulos,0,0,0,0,160,1783,2965,0

In [5]:
print("--- AMOSTRA: TABELA DE ITENS ---")
display(df_itens.head(3))

print("\n--- ESTRUTURA DOS DADOS ---")
df_itens.info()

print("\n--- CONTAGEM DE VALORES NULOS ---")
display(df_itens.isnull().sum().to_frame("Nulos").T)

--- AMOSTRA: TABELA DE ITENS ---

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

--- ESTRUTURA DOS DADOS ---
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

--- CONTAGEM DE VALORES NULOS ---

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
Nulos,0,0,0,0,0,0,0